development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 2
  username: postgres
  password: 'dev4608'

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: postgres
  password: 'dev4608'


